### ISSUE TITLE
Issue with site 

### ISSUE THREAD

**Issue by cmfwebsolutions** [strangerstudios/pmpro-network#12]
Our Main site is at http://domain.com and our subsites are created using subdomain method.
Issue is if the site credits are 0 and the user registers(which is a level option to register without site) they get allocated a site http://.domain.com
how do we stop the dot!

**Comment by strangerstudios** [comment]
It's been a while, but we would need to gain access to your specific site to figure out why this was happening. I hope you were able to get help, but if not we can help in the paid forums here http://www.paidmembershipspro.com

If you figure out the issue on your own, let us know what happened. Thanks.

**Comment by strangerstudios** [comment]
Thanks again for posting this issue... last year. Version .5 has a fix for this. Pushing it out ASAP
