### ISSUE TITLE
Malformed sitename allowed

### ISSUE THREAD

**Issue by chriscappo** [strangerstudios/pmpro-network#13]
In the function `pmpron_addSite($sitename, $sitetitle)` this line of code (currently line 271 in the file):

`$blog_id = wpmu_create_blog($site, $path, $sitetitle, $current_user->ID, $meta);`

At this point, from the checkout page the user could have put in <strong>"...."</strong> as the the site name -- and PMPro will just take that input and use it in the resulting call to `wpmu_create_blog( )` .

I've already had one customer create a mal-formed multisite that is causing SSL errors.  

Do you think the function should make a call to WP function `wpmu_validate_blog_signup( )`?

It seems like that would give the opportunity to return a `WP_Error` object and avoid this problem.

I'm really surprised that this hasn't come up much earlier across your user base, which makes me think I'm missing something -- but I stepped through the code and I can't see where the site name has any opportunity to be filtered before WP takes it and goes off to create the new blog.

I see a similar issue on username -- it's taking anything, no validation.

**Comment by andrewlimaza** [comment]
This issue has been resolved with the latest version.
