### ISSUE TITLE
Make Member Network Sites translation ready

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-network#19]
A member has requested for Member Network Sites to have support for translations in this [support ticket (moderators only)](https://www.paidmembershipspro.com/forums/topic/missing-translation-files/) .

For example:
"You have used 1 of 5 site credits"
"Add a Site"
"Site Name"
"Site Title"
"Add Site" 
"Your Sites"
"Name" 

Screenshot:
![image](https://user-images.githubusercontent.com/4752949/105609282-860fbf80-5da8-11eb-9c0d-bf4a8960e392.png)

Related to https://github.com/strangerstudios/pmpro-network/issues/20

**Comment by kimcoleman** [comment]
This should all be complete in https://github.com/strangerstudios/pmpro-network/pull/22/files
