### ISSUE TITLE
it's giving critical error on my website at checkout.

### ISSUE THREAD

**Issue by asdfg333** [strangerstudios/pmpro-network#29]
it's giving a critical error when I go for checkout on the Elementor website. when I deactivate it works without any problem. so I looked at the error and found that this addon was the cause.

**Comment by andrewlimaza** [comment]
Hi @asdfg333 

Thanks for reaching out, would you mind opening up a support ticket on www.paidmembershipspro.com/support so I team can look into this further for you?

We don't offer support on GitHub via issues of this nature. When creating the support ticket, please include the Site Health information and debug information and we'll be able to assist you further.
