### ISSUE TITLE
Undefined Variable errors

### ISSUE THREAD

**Issue by alexcavender** [strangerstudios/pmpro-network#3]
I am experiencing these errors running PMPro 1.7.13.1 and Network Site Helper .3.2   running on my local host

Notice: Undefined variable: blogname in /Applications/MAMP/htdocs/beatstore-new/wp-content/plugins/pmpro-network-master/pmpro-network.php on line 72

Notice: Undefined variable: blogname in /Applications/MAMP/htdocs/beatstore-new/wp-content/plugins/pmpro-network-master/pmpro-network.php on line 81

Notice</b>:  Undefined variable: sitename in <b>/Applications/MAMP/htdocs/beatstore-new/wp-content/plugins/pmpro-network-master/pmpro-network.php</b> on line <b>95

Notice</b>:  Undefined variable: sitetitle in <b>/Applications/MAMP/htdocs/beatstore-new/wp-content/plugins/pmpro-network-master/pmpro-network.php</b> on line <b>110</b><br />

**Comment by sandersnick** [comment]
I'm getting similar errors. One a user goes through the checkout process, enters payment info submits, i get these errors:

Notice: Undefined index: blog_id in /wp-content/plugins/pmpro-network-master/pmpro-network.php on line 277

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/pmpro-network-master/pmpro-network.php:277) in /wp-includes/pluggable.php on line 955

Notice: Undefined index: blog_id in /wp-content/plugins/pmpro-network-master/pmpro-network.php on line 139

**Comment by dalareo** [comment]
Any news here?? Same problem

**Comment by dalareo** [comment]
I think that the recent commit solves it.

**Comment by strangerstudios** [comment]
Noticed some other warnings related to this and they should be fixed up in version .5 going out right now. Open a new issue if you notice new warnings.
