### ISSUE TITLE
When user signs up, the 1 credit is not used for their initial site

### ISSUE THREAD

**Issue by aronprins** [strangerstudios/pmpro-network#6]
Hey,

Love the plugin and this extension. I set 1 credit for the level that is used upon signup so they can get 1 site: the one they create during signup.

Now, they get 1 credit AND a site...

How can this be fixed?
Thanks in advance!
Cheers,
Aron

**Comment by andrewlimaza** [comment]
This issue has been resolved with latest version - you are able to pull from the `master` branch.
